name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.8, 3.9]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install groq fulltext
      - name: test declaration
        run: |
          python3 docsum.py docs/declaration.txt
          python3 docsum.py docs/news-mx.txt
          for file in docs/*; do python3 docsum.py ${file}; done
